### ISSUE TITLE
Maximize wezterm on launch

### ISSUE THREAD

**Issue by manan-gup** [stepanzak/dotfiles#2]
I cam across your repo while googling about maximizing wezterm.
https://github.com/stepanzak/dotfiles/blob/1eb42a8b05e5c45264c345f51fa30aa56b0fcd0e/dot_config/wezterm/wezterm.lua#L35-L39

The above lines can be replaced by:
```lua
local mux = wezterm.mux

wezterm.on('gui-attached', function(domain)
  -- maximize all displayed windows on startup
  local workspace = mux.get_active_workspace()
  for _, window in ipairs(mux.all_windows()) do
    if window:get_workspace() == workspace then
      window:gui_window():maximize()
    end
  end
end)
```
Copied from [here](https://wezfurlong.org/wezterm/config/lua/gui-events/gui-attached.html).

**Comment by manan-gup** [comment]
There's also
```lua
wezterm.on('gui-startup', function(cmd)
  local tab, pane, window = mux.spawn_window(cmd or {})
  window:gui_window():maximize()
end)
```
which seems cleaner to me but the snippet above is noticeably faster.

**Comment by stepanzak** [comment]
Thank you for creating this issue!
Sadly, I have tried this and it causes ugly and visible resizing.
Here is my screen recording:
https://github.com/stepanzak/dotfiles/assets/99094176/130c5c2f-518a-46e0-a213-3d0710726177
Please ignore the blinking, that's some OBS problem.
Does this resizing happen on your computer? If not, it may be specific to my OS or DE.

**Comment by manan-gup** [comment]
You're right. I tried using the rows and cols method and it just blinks into existence instead of animating. But, the rows and cols method doesn't actually maximize the window, it just resizes it. Also, I'm on KDE and the maximize animation is much smoother than the one in your video. So, it works for me.

Sorry, I couldn't be more help here. You can close this if you want.
